### ISSUE TITLE
NullPointerException in tools.aqua.bgw.builder.Frontend$Companion.sizeChanged

### ISSUE THREAD

**Issue by Chasethechicken** [tudo-aqua/bgw#170]
Sometimes a NullPointerException is thrown in tools.aqua.bgw.builder.Frontend$Companion.sizeChanged

I don't have a minimal demonstration of this right now, but
https://sopra-gitlab.cs.tu-dortmund.de/sopra21C/forks/01-falk-rehse/-/tree/v0.3-nullpointer
can reproduce this issue consistently.
Just start the game, click on "start" and then click on "pass".
A NullPointerException should be thrown in  tools.aqua.bgw.builder.Frontend$Companion.sizeChanged.

`java.lang.NullPointerException
	at tools.aqua.bgw.builder.Frontend$Companion.sizeChanged$lambda-26(Frontend.kt:538)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException
	at tools.aqua.bgw.builder.Frontend$Companion.sizeChanged$lambda-26(Frontend.kt:538)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication.enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication._enterNestedEventLoop(GtkApplication.java:347)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:509)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:634)
	at javafx.stage.Stage.showAndWait(Stage.java:465)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
	at tools.aqua.bgw.builder.Frontend$Companion.showDialog$bgw_core(Frontend.kt:412)
	at tools.aqua.bgw.builder.Frontend.start$lambda-0(Frontend.kt:65)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1074)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1069)
	at com.sun.glass.ui.Application.reportException(Application.java:451)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:831)`

Please complete the following information):
 - OS: Fedora 34
 - Java version: openJDK16 / openJDK11

**Comment by dominikmaeckel** [comment]
The bug is not consistently reproducable on all devices as it is related to a race condition between BGW and the FX renderer. Depending on the OS (specifically Linux machines) and hardware acceleration, this leads to slow rendering and race conditions.

The bug should be fixed in v0.4 anyways by calculating the correct scene pane synchronously and using null-safe access.
