### ISSUE TITLE
Changing `GameScene` in `onDragDropped` causes `IllegalStateException`

### ISSUE THREAD

**Issue by MonsterDruide1** [tudo-aqua/bgw#322]
**Describe the bug**
Using a `onDragDropped`-handler to change the GameScene causes an `IllegalStateException`, still changing the scene.

**To Reproduce**
1. Open the following scene:
```kotlin
import tools.aqua.bgw.components.gamecomponentviews.CardView
import tools.aqua.bgw.core.BoardGameScene
import tools.aqua.bgw.visual.TextVisual

class DropChangeSceneExampleClass(val handler: (() -> Unit)) : BoardGameScene() {

    private val dragLabel = CardView(200, height/2, front=TextVisual("Drag this"))
    private val dropLabel = CardView(500, height/2, front=TextVisual("Here"))


    init {
        addComponents(dragLabel, dropLabel)

        dragLabel.isDraggable = true
        dropLabel.dropAcceptor = { true }
        dropLabel.onDragDropped = {
            handler()
        }
    }

}
```

using this snippet to start it:
```kotlin
fun openTest() {
        showGameScene(DropChangeSceneExampleClass() { openTest() })
}
```

2. Drag the first label to the second one
3. See error

**Expected behavior**
In this artificial scenario, nothing should happen. In a real game, the scene should change properly without an exception.

**Screenshots**
See the code above, but here is a stacktrace:
```
java.lang.IllegalStateException: Required value was null.
	at tools.aqua.bgw.builder.Frontend$Companion.mapToPane$bgw_gui(Frontend.kt:290)
	at tools.aqua.bgw.builder.SceneBuilder.removeDraggedComponent(SceneBuilder.kt:254)
	at tools.aqua.bgw.builder.SceneBuilder.refreshDraggedComponent(SceneBuilder.kt:235)
	at tools.aqua.bgw.builder.SceneBuilder.access$refreshDraggedComponent(SceneBuilder.kt:36)
	at tools.aqua.bgw.builder.SceneBuilder$buildGame$1.invoke(SceneBuilder.kt:47)
	at tools.aqua.bgw.builder.SceneBuilder$buildGame$1.invoke(SceneBuilder.kt:44)
	at tools.aqua.bgw.observable.ValueObservable$sam$tools_aqua_bgw_observable_ValueObserver$0.update(ValueObservable.kt)
	at tools.aqua.bgw.observable.ValueObservable.notifyChange$bgw_gui(ValueObservable.kt:144)
	at tools.aqua.bgw.observable.properties.ReadonlyProperty.setValue$bgw_gui(ReadonlyProperty.kt:44)
	at tools.aqua.bgw.observable.properties.Property.setValue(Property.kt:34)
	at tools.aqua.bgw.builder.SceneBuilder.onMouseReleased(SceneBuilder.kt:190)
	at tools.aqua.bgw.builder.SceneBuilder.buildGame$lambda-1(SceneBuilder.kt:51)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
	at com.sun.glass.ui.View.notifyMouse(View.java:943)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Please complete the following information):
 - OS: Windows 10
 - Java version: Oracle JDK 16

**Additional context**
This does happen in a real game, for example when changing to a GameOver scene after a player has finished their move by swapping cards using a drag.

**Comment by dominikmaeckel** [comment]
This bug has already been fixed in 9cc5ec556948cd71274c4891c4caebfc3dc57b0c.
